// apps/react-demo/src/app.tsx
import { StackRoutes } from '@stacknav/react/react-router';
import { useMemo } from 'react';
import { api } from './demos/fake-api';
import { prefs } from './demos/shared';
import { useStore } from './demos/store';
import { routes } from './routes';

export function App() {
  const { slow, anywhere } = useStore(prefs);
  const busy = useStore(api.inflight) > 0;
  // The Lab's settings, applied to the engine through the outlet's props. Both
  // are plain JS options; `--sn-time-scale` on the container would do the same
  // for the first one from CSS.
  const transition = useMemo(() => ({ timeScale: slow ? 4 : 1 }), [slow]);
  const gesture = useMemo(() => ({ anywhere }), [anywhere]);

  return (
    <div className="phone">
      {/* A thin bar over the outlet: chrome that lives outside the stack and animates independently. */}
      <div className={busy ? 'progress on' : 'progress'} aria-hidden={!busy} />
      <StackRoutes className="outlet" transition={transition} gesture={gesture}>
        {routes}
      </StackRoutes>
    </div>
  );
}

// apps/angular-demo/src/app/app.ts
import { Component, afterRenderEffect, computed, inject, viewChild } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { NavigationCancel, NavigationEnd, NavigationError, NavigationSkipped, NavigationStart, Router } from '@angular/router';
import { StackNavOutlet } from '@stacknav/angular';
import { filter, map } from 'rxjs';
import { FakeApi } from './demos/fake-api';
import { DemoPrefs } from './demos/shared';

@Component({
  selector: 'app-root',
  imports: [StackNavOutlet],
  template: `
    <div class="phone">
      <div class="progress" [class.on]="busy()" [attr.aria-hidden]="!busy()"></div>
      <sn-outlet />
    </div>
  `,
})
export class App {
  private readonly outlet = viewChild.required(StackNavOutlet);
  private readonly prefs = inject(DemoPrefs);
  private readonly api = inject(FakeApi);
  private readonly router = inject(Router);
  /** True while the router is between NavigationStart and its end, which covers resolvers and lazy chunks. */
  private readonly navigating = toSignal(
    this.router.events.pipe(
      map((e) => (e instanceof NavigationStart ? true : e instanceof NavigationEnd || e instanceof NavigationCancel || e instanceof NavigationError || e instanceof NavigationSkipped ? false : null)),
      filter((v): v is boolean => v !== null),
    ),
    { initialValue: false },
  );
  /** A thin bar over the outlet: chrome that lives outside the stack and animates independently. */
  readonly busy = computed(() => this.navigating() || this.api.inflight() > 0);

  constructor() {
    // The Lab's settings are applied directly to the engine the outlet created.
    afterRenderEffect(() => {
      const { stack } = this.outlet();
      stack.transition.options.timeScale = this.prefs.slow() ? 4 : 1;
      stack.gesture.options.anywhere = this.prefs.anywhere();
      stack.gesture.refresh();
    });
  }
}
