// apps/angular-demo/src/app/demos/feed/feed.ts
import { DecimalPipe } from '@angular/common';
import { Component, computed, inject, input, resource, signal } from '@angular/core';
import { FakeApi, type Post } from '../fake-api';
import { BackButton, DEMO_UI } from '../shared';

/** One post rendered as a card. Used by the list, the post page and the profile. */
@Component({
  selector: 'feed-card',
  imports: [...DEMO_UI],
  template: `
    <a class="feed-author" [pushTo]="['/feed/user', post().author.handle]">
      <demo-avatar [name]="post().author.name" [hue]="post().author.hue" [size]="36" />
      <span><b>{{ post().author.name }}</b><small>&#64;{{ post().author.handle }} · {{ ago() }}</small></span>
    </a>
    <p>{{ post().text }}</p>
    @if (post().image; as img) {
      <div class="feed-image" [style.background]="'linear-gradient(135deg, hsl(' + img[0] + ' 70% 60%), hsl(' + img[1] + ' 70% 40%))'"></div>
    }
    <div class="feed-actions">
      <button type="button" (click)="like()" [class.on]="liked()">{{ liked() ? '♥' : '♡' }} {{ post().likes + (liked() ? 1 : 0) }}</button>
      <a [pushTo]="['/feed/post', post().id]">◌ {{ post().comments }}</a>
      <span>↗ share</span>
    </div>
  `,
  host: { class: 'feed-card' },
})
export class FeedCard {
  readonly post = input.required<Post>();
  readonly liked = signal(false);
  readonly ago = computed(() => {
    const m = this.post().minutesAgo;
    return m < 60 ? `${m}m` : m < 60 * 24 ? `${Math.floor(m / 60)}h` : `${Math.floor(m / 1440)}d`;
  });
  like(): void {
    this.liked.update((v) => !v);
  }
}

/**
 * A social timeline: the first page loads behind a shimmering skeleton, more
 * pages append on demand, and every kept card remembers its likes.
 */
@Component({
  selector: 'feed-home',
  imports: [FeedCard, BackButton, ...DEMO_UI],
  template: `
    <div class="page feed">
      <header class="hdr feed-hdr">
        <button type="button" class="back" snBack="/">‹ Demos</button>
        <h1>Feed</h1>
        <button type="button" class="feed-refresh" (click)="refresh()" [disabled]="loading()" aria-label="Refresh">↻</button>
      </header>
      @if (error(); as e) {
        <demo-error [error]="e" (retry)="refresh()" />
      }
      @for (post of posts(); track post.id) {
        <feed-card [post]="post" />
      }
      @if (loading()) {
        <demo-skeleton [lines]="4" />
        <demo-skeleton [lines]="3" />
        <demo-skeleton [lines]="4" />
      } @else if (!error()) {
        <div class="feed-more">
          @if (done()) {
            <span>You're all caught up.</span>
          } @else {
            <button type="button" (click)="more()">Load more</button>
          }
        </div>
      }
    </div>
  `,
})
export class FeedHome {
  private readonly api = inject(FakeApi);
  readonly posts = signal<Post[]>([]);
  readonly loading = signal(false);
  readonly error = signal<unknown>(null);
  readonly done = signal(false);
  private page = 0;

  constructor() {
    void this.more();
  }

  async more(): Promise<void> {
    if (this.loading()) return;
    this.loading.set(true);
    this.error.set(null);
    try {
      const batch = await this.api.posts(this.page);
      this.posts.update((p) => [...p, ...batch]);
      this.page++;
      if (batch.length < 10) this.done.set(true);
    } catch (e) {
      this.error.set(e);
    } finally {
      this.loading.set(false);
    }
  }

  refresh(): void {
    this.posts.set([]);
    this.page = 0;
    this.done.set(false);
    void this.more();
  }
}

/** A post whose comments load shortly after the page, with a reply box at the bottom. */
@Component({
  selector: 'feed-post',
  imports: [FeedCard, BackButton, ...DEMO_UI],
  template: `
    <div class="page feed">
      <header class="hdr feed-hdr">
        <button type="button" class="back" snBack="/feed">‹ Back</button>
        <h1>Post</h1>
        <span class="spacer"></span>
      </header>
      @if (post.isLoading()) {
        <demo-skeleton [lines]="4" />
      } @else if (post.error(); as e) {
        <demo-error [error]="e" (retry)="post.reload()" />
      } @else if (post.hasValue()) {
        <feed-card [post]="post.value()" />
        <h2 class="feed-h2">Comments</h2>
        @if (comments.isLoading()) {
          <demo-skeleton [lines]="2" />
          <demo-skeleton [lines]="2" />
        } @else if (comments.error(); as e) {
          <demo-error [error]="e" (retry)="comments.reload()" />
        } @else if (comments.hasValue()) {
          @for (c of comments.value(); track c.id) {
            <div class="feed-comment">
              <demo-avatar [name]="c.author.name" [hue]="c.author.hue" [size]="28" />
              <div><b>{{ c.author.name }}</b><p>{{ c.text }}</p></div>
            </div>
          }
          @for (c of mine(); track $index) {
            <div class="feed-comment mine">
              <demo-avatar name="You" [hue]="200" [size]="28" />
              <div><b>You</b><p>{{ c }}</p></div>
            </div>
          }
        }
        <form class="feed-reply" (submit)="reply($event)">
          <input name="reply" placeholder="Write a reply…" [value]="draft()" (input)="draft.set($any($event.target).value)" />
          <button type="submit" [disabled]="!draft().trim()">Post</button>
        </form>
      }
    </div>
  `,
})
export class FeedPost {
  readonly id = input.required<string>();
  private readonly api = inject(FakeApi);
  readonly post = resource({ params: () => Number(this.id()), loader: ({ params }) => this.api.post(params) });
  readonly comments = resource({ params: () => Number(this.id()), loader: ({ params }) => this.api.comments(params) });
  readonly draft = signal('');
  readonly mine = signal<string[]>([]);

  reply(e: Event): void {
    e.preventDefault();
    const text = this.draft().trim();
    if (!text) return;
    this.mine.update((m) => [...m, text]);
    this.draft.set('');
  }
}

/** A profile with a cover, stats and tabs. Posts link back to post pages, always as a push. */
@Component({
  selector: 'feed-profile',
  imports: [FeedCard, BackButton, DecimalPipe, ...DEMO_UI],
  template: `
    <div class="page feed">
      <header class="hdr feed-hdr feed-hdr-over">
        <button type="button" class="back" snBack="/feed">‹ Back</button>
        <h1>{{ author.hasValue() ? author.value().name : 'Profile' }}</h1>
        <span class="spacer"></span>
      </header>
      <div class="feed-cover" [style.background]="cover()"></div>
      @if (author.isLoading()) {
        <demo-skeleton [lines]="3" />
      } @else if (author.error(); as e) {
        <demo-error [error]="e" (retry)="author.reload()" />
      } @else if (author.hasValue()) {
        <div class="feed-profile">
          <demo-avatar [name]="author.value().name" [hue]="author.value().hue" [size]="72" />
          <button type="button" class="feed-follow" [class.on]="following()" (click)="following.set(!following())">{{ following() ? 'Following' : 'Follow' }}</button>
          <h2>{{ author.value().name }}</h2>
          <small>&#64;{{ author.value().handle }}</small>
          <p>{{ author.value().bio }}</p>
          <div class="feed-stats">
            <span><b>{{ author.value().followers | number }}</b> followers</span>
            <span><b>{{ author.value().following | number }}</b> following</span>
          </div>
        </div>
        <div class="feed-tabs" role="tablist">
          @for (t of tabs; track t) {
            <button type="button" role="tab" [attr.aria-selected]="tab() === t" (click)="tab.set(t)">{{ t }}</button>
          }
        </div>
        @if (posts.isLoading()) {
          <demo-skeleton [lines]="3" />
          <demo-skeleton [lines]="3" />
        } @else if (posts.hasValue()) {
          @for (post of shown(); track post.id) {
            <feed-card [post]="post" />
          } @empty {
            <p class="feed-empty">Nothing here yet.</p>
          }
        }
      }
    </div>
  `,
})
export class FeedProfile {
  readonly handle = input.required<string>();
  private readonly api = inject(FakeApi);
  readonly author = resource({ params: () => this.handle(), loader: ({ params }) => this.api.author(params) });
  readonly posts = resource({ params: () => this.handle(), loader: ({ params }) => this.api.authorPosts(params) });
  readonly tabs = ['Posts', 'Media', 'Likes'] as const;
  readonly tab = signal<(typeof this.tabs)[number]>('Posts');
  readonly following = signal(false);
  readonly cover = computed(() => {
    const hue = this.author.hasValue() ? this.author.value().hue : 210;
    return `linear-gradient(120deg, hsl(${hue} 60% 45%), hsl(${(hue + 60) % 360} 70% 60%))`;
  });
  readonly shown = computed(() => {
    const all = this.posts.hasValue() ? this.posts.value() : [];
    switch (this.tab()) {
      case 'Media':
        return all.filter((p) => p.image);
      case 'Likes':
        return all.filter((p) => p.likes > 500);
      default:
        return all;
    }
  });
}

// apps/react-demo/src/demos/feed/feed.tsx
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { useParams } from 'react-router';
import { api, type Post } from '../fake-api';
import { Avatar, BackButton, ErrorBox, PushLink, Skeleton, formatNumber, useResource } from '../shared';

const ago = (m: number) => (m < 60 ? `${m}m` : m < 60 * 24 ? `${Math.floor(m / 60)}h` : `${Math.floor(m / 1440)}d`);

/** One post rendered as a card. Used by the list, the post page and the profile. Its like is component state, kept with the page. */
function FeedCard({ post }: { post: Post }) {
  const [liked, setLiked] = useState(false);
  return (
    <div className="feed-card">
      <PushLink className="feed-author" to={`/feed/user/${post.author.handle}`}>
        <Avatar name={post.author.name} hue={post.author.hue} size={36} />
        <span>
          <b>{post.author.name}</b>
          <small>
            @{post.author.handle} · {ago(post.minutesAgo)}
          </small>
        </span>
      </PushLink>
      <p>{post.text}</p>
      {post.image && <div className="feed-image" style={{ background: `linear-gradient(135deg, hsl(${post.image[0]} 70% 60%), hsl(${post.image[1]} 70% 40%))` }} />}
      <div className="feed-actions">
        <button type="button" className={liked ? 'on' : undefined} onClick={() => setLiked((v) => !v)}>
          {liked ? '♥' : '♡'} {post.likes + (liked ? 1 : 0)}
        </button>
        <PushLink to={`/feed/post/${post.id}`}>◌ {post.comments}</PushLink>
        <span>↗ share</span>
      </div>
    </div>
  );
}

/**
 * A social timeline: the first page loads behind a shimmering skeleton, more
 * pages append on demand, and every kept card remembers its likes.
 */
export function FeedHome() {
  const [posts, setPosts] = useState<Post[]>([]);
  const [page, setPage] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<unknown>(null);
  const [done, setDone] = useState(false);
  // Each load takes a ticket; a result whose ticket is stale (a refresh started, or the effect ran twice) is dropped.
  const ticket = useRef(0);

  const load = async (from: number) => {
    const mine = ++ticket.current;
    setLoading(true);
    setError(null);
    try {
      const batch = await api.posts(from);
      if (mine !== ticket.current) return;
      setPosts((p) => [...p, ...batch]);
      setPage(from + 1);
      if (batch.length < 10) setDone(true);
    } catch (e) {
      if (mine === ticket.current) setError(e);
    } finally {
      if (mine === ticket.current) setLoading(false);
    }
  };
  useEffect(() => {
    void load(0);
    return () => {
      ticket.current++;
    };
  }, []);
  const more = () => {
    if (!loading) void load(page);
  };
  const refresh = () => {
    setPosts([]);
    setPage(0);
    setDone(false);
    void load(0);
  };

  return (
    <div className="page feed" data-page="feed">
      <header className="hdr feed-hdr">
        <BackButton to="/">‹ Demos</BackButton>
        <h1>Feed</h1>
        <button type="button" className="feed-refresh" onClick={refresh} disabled={loading} aria-label="Refresh">
          ↻
        </button>
      </header>
      {error != null && <ErrorBox error={error} onRetry={refresh} />}
      {posts.map((post) => (
        <FeedCard key={post.id} post={post} />
      ))}
      {loading ? (
        <>
          <Skeleton lines={4} />
          <Skeleton lines={3} />
          <Skeleton lines={4} />
        </>
      ) : (
        error == null && (
          <div className="feed-more">
            {done ? (
              <span>You're all caught up.</span>
            ) : (
              <button type="button" onClick={more}>
                Load more
              </button>
            )}
          </div>
        )
      )}
    </div>
  );
}

/** A post whose comments load shortly after the page, with a reply box at the bottom. */
export function FeedPost() {
  const { id = '' } = useParams();
  const n = Number(id);
  const post = useResource(() => api.post(n), [n]);
  const comments = useResource(() => api.comments(n), [n]);
  const [draft, setDraft] = useState('');
  const [mine, setMine] = useState<string[]>([]);

  const reply = (e: FormEvent) => {
    e.preventDefault();
    const text = draft.trim();
    if (!text) return;
    setMine((m) => [...m, text]);
    setDraft('');
  };

  return (
    <div className="page feed" data-page="feed-post">
      <header className="hdr feed-hdr">
        <BackButton to="/feed">‹ Back</BackButton>
        <h1>Post</h1>
        <span className="spacer" />
      </header>
      {post.loading ? (
        <Skeleton lines={4} />
      ) : post.error != null ? (
        <ErrorBox error={post.error} onRetry={post.reload} />
      ) : (
        post.value && (
          <>
            <FeedCard post={post.value} />
            <h2 className="feed-h2">Comments</h2>
            {comments.loading ? (
              <>
                <Skeleton lines={2} />
                <Skeleton lines={2} />
              </>
            ) : comments.error != null ? (
              <ErrorBox error={comments.error} onRetry={comments.reload} />
            ) : (
              <>
                {comments.value?.map((c) => (
                  <div key={c.id} className="feed-comment">
                    <Avatar name={c.author.name} hue={c.author.hue} size={28} />
                    <div>
                      <b>{c.author.name}</b>
                      <p>{c.text}</p>
                    </div>
                  </div>
                ))}
                {mine.map((c, i) => (
                  <div key={i} className="feed-comment mine">
                    <Avatar name="You" hue={200} size={28} />
                    <div>
                      <b>You</b>
                      <p>{c}</p>
                    </div>
                  </div>
                ))}
              </>
            )}
            <form className="feed-reply" onSubmit={reply}>
              <input name="reply" placeholder="Write a reply…" value={draft} onChange={(e) => setDraft(e.target.value)} />
              <button type="submit" disabled={!draft.trim()}>
                Post
              </button>
            </form>
          </>
        )
      )}
    </div>
  );
}

const TABS = ['Posts', 'Media', 'Likes'] as const;

/** A profile with a cover, stats and tabs. Posts link back to post pages, always as a push. */
export function FeedProfile() {
  const { handle = '' } = useParams();
  const author = useResource(() => api.author(handle), [handle]);
  const posts = useResource(() => api.authorPosts(handle), [handle]);
  const [tab, setTab] = useState<(typeof TABS)[number]>('Posts');
  const [following, setFollowing] = useState(false);
  const hue = author.value?.hue ?? 210;
  const all = posts.value ?? [];
  const shown = tab === 'Media' ? all.filter((p) => p.image) : tab === 'Likes' ? all.filter((p) => p.likes > 500) : all;

  return (
    <div className="page feed" data-page="feed-profile">
      <header className="hdr feed-hdr feed-hdr-over">
        <BackButton to="/feed">‹ Back</BackButton>
        <h1>{author.value?.name ?? 'Profile'}</h1>
        <span className="spacer" />
      </header>
      <div className="feed-cover" style={{ background: `linear-gradient(120deg, hsl(${hue} 60% 45%), hsl(${(hue + 60) % 360} 70% 60%))` }} />
      {author.loading ? (
        <Skeleton lines={3} />
      ) : author.error != null ? (
        <ErrorBox error={author.error} onRetry={author.reload} />
      ) : (
        author.value && (
          <>
            <div className="feed-profile">
              <Avatar name={author.value.name} hue={author.value.hue} size={72} />
              <button type="button" className={following ? 'feed-follow on' : 'feed-follow'} onClick={() => setFollowing((f) => !f)}>
                {following ? 'Following' : 'Follow'}
              </button>
              <h2>{author.value.name}</h2>
              <small>@{author.value.handle}</small>
              <p>{author.value.bio}</p>
              <div className="feed-stats">
                <span>
                  <b>{formatNumber(author.value.followers)}</b> followers
                </span>
                <span>
                  <b>{formatNumber(author.value.following)}</b> following
                </span>
              </div>
            </div>
            <div className="feed-tabs" role="tablist">
              {TABS.map((t) => (
                <button key={t} type="button" role="tab" aria-selected={tab === t} onClick={() => setTab(t)}>
                  {t}
                </button>
              ))}
            </div>
            {posts.loading ? (
              <>
                <Skeleton lines={3} />
                <Skeleton lines={3} />
              </>
            ) : shown.length ? (
              shown.map((post) => <FeedCard key={post.id} post={post} />)
            ) : (
              <p className="feed-empty">Nothing here yet.</p>
            )}
          </>
        )
      )}
    </div>
  );
}
