// apps/react-demo/src/demos/gallery/gallery.tsx
import { useState, type CSSProperties } from 'react';
import { Link, useParams } from 'react-router';
import { api, type Photo } from '../fake-api';
import { BackButton, Deferred, ErrorBox, PushLink, Skeleton, Spinner, useResource } from '../shared';

const paint = (p: Photo) => `linear-gradient(${p.angle}deg, hsl(${p.hues[0]} 70% 55%), hsl(${p.hues[1]} 65% 35%))`;

/** A dense three-column grid of tiles on a light page. */
export function GalleryGrid() {
  const photos = useResource(() => api.photos(), []);
  const [columns, setColumns] = useState(3);
  return (
    <div className="page gal" data-page="gallery">
      <header className="hdr gal-hdr">
        <BackButton to="/">‹ Demos</BackButton>
        <h1>Gallery</h1>
        <button type="button" className="gal-toggle" onClick={() => setColumns(columns === 3 ? 2 : 3)} aria-label={`Show ${columns === 3 ? 2 : 3} columns`}>
          {columns === 3 ? '▦' : '▤'}
        </button>
      </header>
      {photos.error != null ? (
        <ErrorBox error={photos.error} onRetry={photos.reload} />
      ) : photos.loading ? (
        <div className="gal-grid" style={{ '--cols': columns } as CSSProperties}>
          {Array.from({ length: 18 }, (_, i) => (
            <div key={i} className="gal-tile skel-tile" />
          ))}
        </div>
      ) : (
        <div className="gal-grid" style={{ '--cols': columns } as CSSProperties}>
          {photos.value?.map((p) => (
            <Link key={p.id} className="gal-tile" to={`/gallery/${p.id}`} style={{ background: paint(p) }} aria-label={p.title} />
          ))}
        </div>
      )}
    </div>
  );
}

/**
 * A dark viewer. The filmstrip's links are siblings in the route tree, so they
 * replace this page in place. "Next" is an explicit push, so the stack grows
 * and swiping back retraces the photos you opened. A deferred block loads the
 * details shortly after the page lands.
 */
export function GalleryPhoto() {
  const { id: idParam = '' } = useParams();
  const id = Number(idParam);
  const count = api.photoCount();
  const photo = useResource(() => api.photo(id), [id]);
  const [liked, setLiked] = useState(false);
  const lo = Math.max(1, Math.min(id - 3, count - 6));
  const strip = Array.from({ length: 7 }, (_, i) => lo + i);
  const p = photo.value;

  return (
    <div className="page gal gal-dark" data-page="gallery-photo">
      <header className="hdr gal-hdr-dark">
        <BackButton to="/gallery">‹ Gallery</BackButton>
        <h1>{p?.title ?? 'Photo'}</h1>
        <button type="button" className={liked ? 'gal-like on' : 'gal-like'} onClick={() => setLiked((v) => !v)} aria-label="Like">
          {liked ? '♥' : '♡'}
        </button>
      </header>
      {photo.error != null ? (
        <ErrorBox error={photo.error} onRetry={photo.reload} />
      ) : p ? (
        <>
          <div className="gal-stage">
            <div className="gal-photo" style={{ background: paint(p), aspectRatio: p.ratio }} />
          </div>
          <div className="gal-caption">
            <b>{p.title}</b>
            <span>{p.place}</span>
          </div>
          <Deferred ms={400} placeholder={<Skeleton lines={2} />}>
            <dl className="gal-exif">
              <div>
                <dt>Camera</dt>
                <dd>Fable X100</dd>
              </div>
              <div>
                <dt>Lens</dt>
                <dd>23 mm ƒ/2</dd>
              </div>
              <div>
                <dt>Exposure</dt>
                <dd>1/{60 + p.id * 20} s</dd>
              </div>
              <div>
                <dt>ISO</dt>
                <dd>{100 * (1 + (p.id % 5))}</dd>
              </div>
            </dl>
          </Deferred>
          <div className="gal-strip">
            {strip.map((n) => (
              <Link key={n} to={`/gallery/${n}`} className={n === id ? 'on' : undefined} style={{ background: `hsl(${(n * 47) % 360} 60% 45%)` }} aria-label={`Photo ${n}`} />
            ))}
          </div>
          <div className="gal-nav">
            <span>
              {id} / {count}
            </span>
            {id < count && <PushLink to={`/gallery/${id + 1}`}>Next ›</PushLink>}
          </div>
        </>
      ) : (
        <Spinner />
      )}
    </div>
  );
}

// apps/angular-demo/src/app/demos/gallery/gallery.ts
import { Component, computed, inject, input, resource, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { FakeApi, type Photo } from '../fake-api';
import { BackButton, DEMO_UI } from '../shared';

const paint = (p: Photo) => `linear-gradient(${p.angle}deg, hsl(${p.hues[0]} 70% 55%), hsl(${p.hues[1]} 65% 35%))`;

/** A dense three-column grid of tiles on a light page. */
@Component({
  selector: 'gallery-grid',
  imports: [RouterLink, BackButton, ...DEMO_UI],
  template: `
    <div class="page gal">
      <header class="hdr gal-hdr">
        <button type="button" class="back" snBack="/">‹ Demos</button>
        <h1>Gallery</h1>
        <button type="button" class="gal-toggle" (click)="columns.set(columns() === 3 ? 2 : 3)" [attr.aria-label]="'Show ' + (columns() === 3 ? 2 : 3) + ' columns'">{{ columns() === 3 ? '▦' : '▤' }}</button>
      </header>
      @if (photos.error(); as e) {
        <demo-error [error]="e" (retry)="photos.reload()" />
      } @else if (photos.isLoading()) {
        <div class="gal-grid" [style.--cols]="columns()">
          @for (i of placeholders; track i) {
            <div class="gal-tile skel-tile"></div>
          }
        </div>
      } @else if (photos.hasValue()) {
        <div class="gal-grid" [style.--cols]="columns()">
          @for (p of photos.value(); track p.id) {
            <a class="gal-tile" [routerLink]="['/gallery', p.id]" [style.background]="paint(p)" [attr.aria-label]="p.title"></a>
          }
        </div>
      }
    </div>
  `,
})
export class GalleryGrid {
  private readonly api = inject(FakeApi);
  readonly photos = resource({ loader: () => this.api.photos() });
  readonly columns = signal(3);
  readonly placeholders = Array.from({ length: 18 }, (_, i) => i);
  readonly paint = paint;
}

/**
 * A dark viewer. The filmstrip's links are siblings in the route tree, so they
 * replace this page in place. "Next" is an explicit push, so the stack grows
 * and swiping back retraces the photos you opened. A deferred block loads the
 * details shortly after the page lands.
 */
@Component({
  selector: 'gallery-photo',
  imports: [RouterLink, BackButton, ...DEMO_UI],
  template: `
    <div class="page gal gal-dark">
      <header class="hdr gal-hdr-dark">
        <button type="button" class="back" snBack="/gallery">‹ Gallery</button>
        <h1>{{ photo.hasValue() ? photo.value().title : 'Photo' }}</h1>
        <button type="button" class="gal-like" [class.on]="liked()" (click)="liked.set(!liked())" aria-label="Like">{{ liked() ? '♥' : '♡' }}</button>
      </header>
      @if (photo.error(); as e) {
        <demo-error [error]="e" (retry)="photo.reload()" />
      } @else if (photo.hasValue()) {
        <div class="gal-stage">
          <div class="gal-photo" [style.background]="paint(photo.value())" [style.aspectRatio]="photo.value().ratio"></div>
        </div>
        <div class="gal-caption">
          <b>{{ photo.value().title }}</b>
          <span>{{ photo.value().place }}</span>
        </div>
        @defer (on timer(400ms)) {
          <dl class="gal-exif">
            <div><dt>Camera</dt><dd>Fable X100</dd></div>
            <div><dt>Lens</dt><dd>23 mm ƒ/2</dd></div>
            <div><dt>Exposure</dt><dd>1/{{ 60 + photo.value().id * 20 }} s</dd></div>
            <div><dt>ISO</dt><dd>{{ 100 * (1 + (photo.value().id % 5)) }}</dd></div>
          </dl>
        } @placeholder {
          <demo-skeleton [lines]="2" />
        }
        <div class="gal-strip">
          @for (n of strip(); track n) {
            <a [routerLink]="['/gallery', n]" [class.on]="n === id()" [style.background]="'hsl(' + ((n * 47) % 360) + ' 60% 45%)'" [attr.aria-label]="'Photo ' + n"></a>
          }
        </div>
        <div class="gal-nav">
          <span>{{ id() }} / {{ count }}</span>
          @if (id() < count) {
            <a [pushTo]="['/gallery', id() + 1]">Next ›</a>
          }
        </div>
      } @else {
        <demo-spinner />
      }
    </div>
  `,
})
export class GalleryPhoto {
  readonly idParam = input.required<string>({ alias: 'id' });
  private readonly api = inject(FakeApi);
  readonly id = computed(() => Number(this.idParam()));
  readonly count = this.api.photoCount();
  readonly photo = resource({ params: () => this.id(), loader: ({ params }) => this.api.photo(params) });
  readonly liked = signal(false);
  readonly strip = computed(() => {
    const lo = Math.max(1, Math.min(this.id() - 3, this.count - 6));
    return Array.from({ length: 7 }, (_, i) => lo + i);
  });
  readonly paint = paint;
}
