// apps/react-demo/src/pages/about.tsx
import { Link } from 'react-router';
import { useBack } from '../back';

export function About() {
  const back = useBack();
  return (
    <div className="page" data-page="about">
      <header className="hdr">
        <button type="button" className="back" onClick={() => back('/settings')}>
          ‹ Back
        </button>
        <h1>About</h1>
        <span className="spacer" />
      </header>
      <div className="body">
        <p className="lede">
          <code>stackLevel = 3</code>. Nothing here is prescribed by the engine: the numbers live on your routes.
        </p>
        <Link className="item" to="/settings">
          <span>Settings</span>
          <small>pop: 3 → 2</small>
          <i>›</i>
        </Link>
      </div>
    </div>
  );
}

// apps/angular-demo/src/app/pages/about.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { useBack } from '../back';

@Component({
  selector: 'app-about',
  imports: [RouterLink],
  template: `
    <div class="page">
      <header class="hdr"><button type="button" class="back" (click)="back(['/settings'])">‹ Back</button><h1>About</h1><span class="spacer"></span></header>
      <div class="body">
        <p class="lede"><code>stackLevel = 3</code>. Nothing here is prescribed by the engine: the numbers live on your routes.</p>
        <a class="item" routerLink="/settings"><span>Settings</span><small>pop: 3 → 2</small><i>›</i></a>
      </div>
    </div>
  `,
})
export class About {
  readonly back = useBack();
}
