// apps/react-demo/src/demos/shared.tsx
import { useStackNav } from '@stacknav/react';
import { useCallback, useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { Link, useNavigate, type LinkProps } from 'react-router';
import { useBack } from '../back';
import { initials } from './fake-api';
import { createStore } from './store';

/** Settings the Lab page changes. The App applies them to the outlet. */
export const prefs = createStore({
  /** 4x slower transitions, for inspecting a transition mid-flight. */
  slow: false,
  /** Start the back gesture from anywhere on the page, not only the leading edge. */
  anywhere: false,
});

/**
 * "Pop to root": goes back to a page still kept beneath, unwinding history by
 * as many entries as there are pages above it. The demos push one history entry
 * per page, and replaced pages use `replace`, so the counts match and a browser
 * back afterwards lands on the expected page.
 */
export function usePopTo(): (path: string) => void {
  const { pages } = useStackNav();
  const navigate = useNavigate();
  return useCallback(
    (path: string) => {
      const i = pages.findIndex((p) => p.route.location.pathname === path);
      if (i >= 0 && i < pages.length - 1) void navigate(i - (pages.length - 1));
      else void navigate(path, { replace: true, state: { stacknav: 'pop' } });
    },
    [pages, navigate],
  );
}

/**
 * `<BackButton to="/shop">`: goes back through history, falling back to that
 * route as a pop after a deep link. The library has no back API of its own;
 * this is the app's `useBack()` in a button, so the demo headers stay short.
 */
export function BackButton({ to, children, className = 'back' }: { to: string; children: ReactNode; className?: string }) {
  const back = useBack();
  return (
    <button type="button" className={className} onClick={() => back(to)}>
      {children}
    </button>
  );
}

/**
 * A link that always pushes, regardless of what the route tree says: the
 * router's own `<Link>` with a hint in its `state`. Useful for flows that can
 * grow without bound (post → author → post → author …), where the tree would
 * treat the cross-links as siblings.
 */
export function PushLink(props: LinkProps) {
  return <Link {...props} state={{ stacknav: 'push', ...(props.state as object | undefined) }} />;
}

export function Avatar({ name, hue, size = 40, style }: { name: string; hue: number; size?: number; style?: CSSProperties }) {
  return (
    <span className="avatar" style={{ background: `hsl(${hue} 55% 52%)`, width: size, height: size, fontSize: size * 0.38, ...style }}>
      {initials(name)}
    </span>
  );
}

/** A loading placeholder: `lines` shimmering grey bars. */
export function Skeleton({ lines = 3 }: { lines?: number }) {
  return (
    <div className="skel" aria-busy="true">
      {Array.from({ length: lines }, (_, i) => (
        <div key={i} className="skel-line" style={{ width: `${[92, 70, 84, 55, 78][i % 5]}%` }} />
      ))}
    </div>
  );
}

/** An error message with a retry button. */
export function ErrorBox({ error, onRetry }: { error: unknown; onRetry: () => void }) {
  return (
    <div className="err" role="alert">
      <strong>Couldn't load.</strong>
      <span>{error instanceof Error ? error.message : String(error)}</span>
      <button type="button" onClick={onRetry}>
        Try again
      </button>
    </div>
  );
}

export function Spinner() {
  return <span className="spinner" role="progressbar" aria-label="Loading" />;
}

export interface Resource<T> {
  value: T | undefined;
  error: unknown;
  loading: boolean;
  reload(): void;
}

/**
 * Loads `load()` whenever `deps` change, ignoring results that arrive after a
 * newer request started. The loaded value is component state, so it lives
 * exactly as long as the page: kept while the page is beneath the top, gone
 * when the page is.
 */
export function useResource<T>(load: () => Promise<T>, deps: readonly unknown[]): Resource<T> {
  const [state, setState] = useState<{ value: T | undefined; error: unknown; loading: boolean }>({ value: undefined, error: null, loading: true });
  const [tick, setTick] = useState(0);
  const loadRef = useRef(load);
  loadRef.current = load;
  useEffect(() => {
    let live = true;
    setState((s) => ({ ...s, error: null, loading: true }));
    loadRef.current().then(
      (value) => live && setState({ value, error: null, loading: false }),
      (error: unknown) => live && setState((s) => ({ ...s, error, loading: false })),
    );
    return () => {
      live = false;
    };
  }, [...deps, tick]);
  const reload = useCallback(() => setTick((t) => t + 1), []);
  return { ...state, reload };
}

/** Renders `children` only after `ms` milliseconds, like a deferred block. */
export function Deferred({ ms, placeholder, children }: { ms: number; placeholder: ReactNode; children: ReactNode }) {
  const [ready, setReady] = useState(false);
  useEffect(() => {
    const t = setTimeout(() => setReady(true), ms);
    return () => clearTimeout(t);
  }, [ms]);
  return <>{ready ? children : placeholder}</>;
}

export const formatNumber = (n: number): string => n.toLocaleString('en-US');

// apps/angular-demo/src/app/demos/shared.ts
import { Location } from '@angular/common';
import { Component, Directive, Injectable, computed, inject, input, output, signal } from '@angular/core';
import { ChildrenOutletContexts, PRIMARY_OUTLET, Router } from '@angular/router';
import { type StackNavOutlet } from '@stacknav/angular';
import { useBack } from '../back';
import { initials } from './fake-api';

/** Settings the Lab page changes. The App applies them to the outlet. */
@Injectable({ providedIn: 'root' })
export class DemoPrefs {
  /** 4x slower transitions, for inspecting a transition mid-flight. */
  readonly slow = signal(false);
  /** Start the back gesture from anywhere on the page, not only the leading edge. */
  readonly anywhere = signal(false);
}

/**
 * "Pop to root": goes back to a page still kept beneath, unwinding history by
 * as many entries as there are pages above it. The demos push one history entry
 * per page, and replaced pages use `replaceUrl`, so the counts match and a
 * browser back afterwards lands on the expected page.
 */
@Injectable({ providedIn: 'root' })
export class DemoNav {
  private readonly router = inject(Router);
  private readonly location = inject(Location);
  private readonly contexts = inject(ChildrenOutletContexts);

  popTo(url: string): void {
    const outlet = this.contexts.getContext(PRIMARY_OUTLET)?.outlet as StackNavOutlet | null;
    const pages = outlet?.pages ?? [];
    const i = pages.findIndex((p) => p.url === url);
    if (i >= 0 && i < pages.length - 1) this.location.historyGo(i - (pages.length - 1));
    else void this.router.navigateByUrl(url, { replaceUrl: true, info: { stacknav: 'pop' } });
  }
}

/**
 * `<button snBack="/shop">`: goes back through history, falling back to that
 * route as a pop after a deep link. The library has no back API of its own.
 * This is the app's `useBack()` wrapped in a directive, so the demo headers stay
 * a single line.
 */
@Directive({
  selector: '[snBack]',
  host: { '(click)': 'onClick($event)' },
})
export class BackButton {
  readonly fallback = input<readonly unknown[] | null, unknown>(null, {
    alias: 'snBack',
    transform: (v: unknown) => (v === '' || v == null ? null : Array.isArray(v) ? (v as readonly unknown[]) : [v]),
  });
  private readonly back = useBack();
  private readonly location = inject(Location);

  onClick(event: Event): void {
    event.preventDefault();
    const fallback = this.fallback();
    if (fallback) this.back(fallback);
    else this.location.back();
  }
}

/**
 * `<a [pushTo]="['/feed/post', 3]">`: a link that always pushes, regardless of
 * what the route tree says. Useful for flows that can grow without bound
 * (post → author → post → author …), where the tree would treat the cross-links
 * as siblings.
 */
@Directive({
  selector: 'a[pushTo]',
  host: { '[attr.href]': 'href()', '(click)': 'onClick($event)' },
})
export class PushLink {
  readonly pushTo = input.required<readonly unknown[]>();
  private readonly router = inject(Router);
  readonly href = computed(() => this.router.serializeUrl(this.router.createUrlTree(this.pushTo() as unknown[])));

  onClick(event: MouseEvent): void {
    if (event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;
    event.preventDefault();
    void this.router.navigate([...this.pushTo()], { info: { stacknav: 'push' } });
  }
}

@Component({
  selector: 'demo-avatar',
  template: `{{ text() }}`,
  host: {
    class: 'avatar',
    '[style.background]': '"hsl(" + hue() + " 55% 52%)"',
    '[style.width.px]': 'size()',
    '[style.height.px]': 'size()',
    '[style.fontSize.px]': 'size() * 0.38',
  },
})
export class Avatar {
  readonly name = input.required<string>();
  readonly hue = input.required<number>();
  readonly size = input(40);
  readonly text = computed(() => initials(this.name()));
}

/** A loading placeholder: `[lines]` shimmering grey bars. */
@Component({
  selector: 'demo-skeleton',
  template: `
    @for (w of widths(); track $index) {
      <div class="skel-line" [style.width.%]="w"></div>
    }
  `,
  host: { class: 'skel', 'aria-busy': 'true' },
})
export class Skeleton {
  readonly lines = input(3);
  readonly widths = computed(() => Array.from({ length: this.lines() }, (_, i) => [92, 70, 84, 55, 78][i % 5]));
}

/** An error message with a retry button. */
@Component({
  selector: 'demo-error',
  template: `
    <strong>Couldn't load.</strong>
    <span>{{ message() }}</span>
    <button type="button" (click)="retry.emit()">Try again</button>
  `,
  host: { class: 'err', role: 'alert' },
})
export class ErrorBox {
  readonly error = input.required<unknown>();
  readonly retry = output();
  readonly message = computed(() => (this.error() instanceof Error ? (this.error() as Error).message : String(this.error())));
}

@Component({
  selector: 'demo-spinner',
  template: '',
  host: { class: 'spinner', role: 'progressbar', 'aria-label': 'Loading' },
})
export class Spinner {}

export const DEMO_UI = [Avatar, Skeleton, ErrorBox, Spinner, PushLink, BackButton] as const;
