// apps/angular-demo/src/app/pages/reviews.ts
import { Component, input, signal } from '@angular/core';
import { useBack } from '../back';

@Component({
  selector: 'app-reviews',
  template: `
    <div class="page">
      <header class="hdr"><button type="button" class="back" (click)="back(['/items', id()])">‹ Item {{ id() }}</button><h1>Reviews</h1><span class="spacer"></span></header>
      <div class="body">
        <p class="lede">Three levels deep. Swipe from the left edge, press the browser back button, or tap Back: all three pop.</p>
        @for (r of reviews; track r) {<div class="item"><span>{{ r }}</span></div>}
        <h2>Guards</h2>
        <label class="item"><span>Block leaving (canDeactivate)</span><input type="checkbox" [checked]="lock()" (change)="lock.set($any($event.target).checked)"></label>
        <p class="lede">With this on, a swipe or back press is refused by the router and the page settles back into place.</p>
      </div>
    </div>
  `,
})
export class Reviews {
  readonly id = input.required<string>();
  readonly lock = signal(false);
  readonly reviews = [
    'Five stars, would push again.',
    'Popped right back where I was.',
    'The parallax is subtle. I like it.',
  ];
  readonly back = useBack();
}

// apps/react-demo/src/pages/reviews.tsx
import { useLocation, useParams } from 'react-router';
import { useBack } from '../back';

const REVIEWS = ['Five stars, would push again.', 'Popped right back where I was.', 'The parallax is subtle. I like it.'];

export function Reviews() {
  const { id = '' } = useParams();
  const location = useLocation();
  const back = useBack();
  return (
    <div className="page" data-page="reviews">
      <header className="hdr">
        <button type="button" className="back" onClick={() => back(`/items/${id}`)}>
          ‹ Item {id}
        </button>
        <h1>Reviews</h1>
        <span className="spacer" />
      </header>
      <div className="body">
        <p className="lede">Three levels deep. Swipe from the left edge, press the browser back button, or tap Back: all three pop.</p>
        {REVIEWS.map((r) => (
          <div key={r} className="item">
            <span>{r}</span>
          </div>
        ))}
        <h2>Frozen location</h2>
        <p className="lede">
          <code>useLocation()</code> says <code>{location.pathname}</code>. While this page is kept beneath another, it keeps saying so: pages beneath the top are rendered at the location they were reached at.
        </p>
      </div>
    </div>
  );
}
